[
uuid(38E5E1B7-4D07-4568-B274-F312B7CE5775),
version(1.0)
]
interface BochsDebug
{
#include "BochsRpcDataTypes.h"

void Bochs_PauseSimulation([in] handle_t h1);
void Bochs_ResumeSimulation([in] handle_t h1);
void Bochs_QuitSimulation([in] handle_t h1);
boolean Bochs_ReadLinearMemory([in] handle_t h1, [in] unsigned __int64 StartAddr, [in] unsigned __int32 Length, [out, ref, size_is(Length)] byte Buffer[]);
boolean Bochs_ReadPhysicalMemory([in] handle_t h1, [in] unsigned __int64 StartAddr, [in] unsigned __int32 Length, [out, ref, size_is(Length)] byte Buffer[]);
void Bochs_WaitForIdle([in] handle_t h1);
void Bochs_PrintRegs([in] handle_t h1);
void Bochs_GetGPRs([in] handle_t h1, [out, ref] PBochsGPRsContext context);
[string, unique] char* Bochs_GetVersion([in] handle_t h1);
}
