[
uuid(38E5E1B7-4D07-4568-B274-F312B7CE5775),
version(1.0)
]
interface BochsDebug
{
typedef struct _BochsGPRsContext{
	unsigned __int32 EAX;
	unsigned __int32 ECX;
	unsigned __int32 EDX;
	unsigned __int32 EBX;
	unsigned __int32 ESP;
	unsigned __int32 EBP;
	unsigned __int32 ESI;
	unsigned __int32 EDI;
	unsigned __int32 EIP;
	unsigned __int32 EFLAGS;
}BochsGPRsContext, *PBochsGPRsContext;

void Bochs_PauseSimulation([in] handle_t h1);
void Bochs_ResumeSimulation([in] handle_t h1);
void Bochs_QuitSimulation([in] handle_t h1);
error_status_t Bochs_ReadLinearMemory([in] handle_t h1, [in] unsigned __int32 StartAddr, [in] unsigned __int32 Length, [out, ref, size_is(Length)] byte Buffer[]);
error_status_t Bochs_ReadPhysicalMemory([in] handle_t h1, [in] unsigned __int32 StartAddr, [in] unsigned __int32 Length, [out, ref, size_is(Length)] byte Buffer[]);
void Bochs_WaitForIdle([in] handle_t h1);
error_status_t Bochs_GetGPRs([in] handle_t h1, [out, ref] PBochsGPRsContext context);
}
